/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    REACT_FIREBASE_API_KEY: process.env.REACT_FIREBASE_API_KEY,
    REACT_FIREBASE_AUTH_DOMAIN: process.env.REACT_FIREBASE_AUTH_DOMAIN,
    REACT_FIREBASE_APP_PROJECT_ID: process.env.REACT_FIREBASE_APP_PROJECT_ID,
    REACT_FIREBASE_STORAGE_BUCKET: process.env.REACT_FIREBASE_STORAGE_BUCKET,
    REACT_FIREBASE_MESSAGING_SENDER_ID:
      process.env.REACT_FIREBASE_MESSAGING_SENDER_ID,
    REACT_FIREBASE_APP_ID: process.env.REACT_FIREBASE_APP_ID,
    REACT_FIREBASE_MEASUREMENT_ID: process.env.REACT_FIREBASE_MEASUREMENT_ID,
    REACT_SANITY_PROJECT_ID: process.env.REACT_SANITY_PROJECT_ID,
    REACT_SANITY_API_TOKEN: process.env.REACT_SANITY_API_TOKEN,
    REACT_CLASSROOM_DEFAULT_IMAGE_ID:
      process.env.REACT_CLASSROOM_DEFAULT_IMAGE_ID
  }
};

module.exports = nextConfig;
