import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import AuthContextProvider from '../src/contexts/AuthContext'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
      <div className={styles.container}>
      <Head>
        <title>Gramática avançada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Link href="/login">
          <a>Login</a>
        </Link>
      </main>

    </div>
    
  )
}

export default Home
